services:
  # Demo Site only!
  # Make sure to remove adminer for actual production use
  adminer:
    restart: unless-stopped
    image: adminer:standalone
    ports:
      - 8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pappu687

  inventory_service:
    restart: unless-stopped
    image: ${INVENTORY_SERVICE_IMAGE_NAME}:${INVENTORY_SERVICE_IMAGE_VERSION}
    expose:
      - 8000
    environment:
      APP_ENVIRONMENT: ${INVENTORY_SERVICE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      VUE_HOST: ${PWA_DOMAIN}
      ALLOWED_ORIGINS: ${PWA_DOMAIN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 30s

  caddy:
    restart: unless-stopped
    image: ${CADDY_IMAGE_NAME}:${CADDY_IMAGE_VERSION}
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./pwa-dist:/var/www
    depends_on:
      - inventory_service
      - adminer
    environment:
      INVENTORY_SERVICE_DOMAIN: ${INVENTORY_SERVICE_DOMAIN}
      INVENTORY_SERVICE_BACKEND: inventory_service
      INVENTORY_SERVICE_PORT: 8000
      ADMINER_DOMAIN: ${ADMINER_DOMAIN}
      ADMINER_BACKEND: adminer
      ADMINER_PORT: 8080
      PWA_DOMAIN: ${INVENTORY_SERVICE_DOMAIN}

volumes:
  caddy_data:
  caddy_config:
